#!/usr/bin/env bash
# Script to display information about subdomains
if [ "$2" ]
then
  record=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
  destination=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
  echo The subdomain "$2" is a "${record}" record and points to "${destination}"
else
  subdomains=("www" "lb-01" "web-01" "web-02")
  for ((i=0;i<${#subdomains[@]};++i));
  do
    record=$(dig "${subdomains[i]}"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
    destination=$(dig "${subdomains[i]}"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
    echo The subdomain "${subdomains[i]}" is a "${record}" record and points to "${destination}"
  done
fi