#!/usr/bin/env bash
# Script to display information about subdomains


print()
{
  echo The subdomain "${1}" is a "${2}" record and points to "${3}"
}
if [ "$2" ]
then
  record=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
  destination=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
  print ${2} ${record} ${destination}
else
  subdomains=("www" "lb-01" "web-01" "web-02")
  for ((i=0;i<${#subdomains[@]};++i));
  do
    record=$(dig "${subdomains[i]}"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
    destination=$(dig "${subdomains[i]}"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
    print ${subdomains[i]} ${record} ${destination}
  done
fi
