#!/usr/bin/env bash
# Script to install and configure nginx
sudo apt-get -y update && sudo apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
service nginx start
