#!/usr/bin/env bash
# Redirectioning
redirect_me=$(grep "redirect_me" /etc/ngnix/sites-available/default)
if [[ -z $redirect_me ]]; then
sed -i "48i \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
fi