#!/usr/bin/env bash
# redirect me.
apt-get update && apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

REDIRECT_ME=$(grep "redirect_me" /etc/nginx/sites-available/default)
if [[ -z $REDIRECT_ME ]]; then
    COMMAND="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
    # Add line into the file.
    sed -i "48i $COMMAND" /etc/nginx/sites-available/default
fi

service nginx restart
