#!/usr/bin/env bash
# NO FOUND THE PAGE 404
apt-get update && apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

found="server_name _;"
adding="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
sed -i "/$found/a\\$adding"


adding="\n\terror_page 404 /404.html;"
sed -i "/$found/a\\$adding"

service nginx restart
