#!/usr/bin/env bash
# Script to Configure servers !!
apt-get update && apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html

found="server_name_;"
adding="\nlocation /redirect_me {\n\t\treturn 301 https://youtube.com;\n\t}"
sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/error404.html
adding="\nterror page 404 /error404.html;\n"
sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default

adding="\nadd_header X-Served-By $HOSTNAME always;"
sed -i "/$found/a\\$adding" /etc/nginx/sites-available/default

service nginx restart
