#!/usr/bin/env bash
# Scrip to display messages when is tried to stop the program
status=1

_term()
{
  echo 'I hate the kill command'
  rm /var/run/holbertonscript.pid
  status=0
}

_int()
{
  echo 'Y U no love me?!'
  rm /var/run/holbertonscript.pid
  status=0
}

trap _term SIGTERM
trap _int SIGINT

while [ $status == 1 ]
do
  echo 'To infinity and beyond'
  sleep 2
done