#!/usr/bin/env bash
# Script to show a message infinitely and other when sigterm is ocurred
_term()
{
  echo 'I am invincible!!!'
}

trap _term SIGTERM

while [ 1 ]
do
  echo 'To infinity and beyond'
  sleep 2
done