#!/usr/bin/env bash
# Script to iterate 20 times and show messages depend of position
x=1

while [ $x -le 20 ]
do
  echo $x
  case $x in
    4) echo 'bad luck from China';;
    9) echo 'bad luck from Japan';;
    17) echo 'bad luck from Italy';;
  esac
 x=$(( x + 1 ))
done