#!/usr/bin/env bash
# Script to give you information
FILE=holbertonschool


if [ -f "$FILE" ]
then
  echo 'holbertonschool file exists'
  if [ -s "$FILE" ]
  then
    echo 'holbertonschool is not empty'
  else
    echo 'holbertonschool is empty'
  fi
  if [ -f "$FILE" ]
  then
    echo 'holbertonschool file is a regular file'
  fi
else
  echo 'holbertonschool file does not exist'
fi