#!/usr/bin/env bash
# Script to give you information
FILE=holbertonschool

if [ -f "$FILE" ]
then
  echo 'holbertonschool file exists'
  if [ -s "$FILE" ]
  then
    echo 'holbertonschool file is not empty'
  else
    echo 'holbertonschool file is empty'
  fi
  echo 'holbertonschool file is a regular file'
else
  echo 'holbertonschool file does not exist'
fi