#!/usr/bin/env bash
# Script to execute nginx with root nginx
chown -R nginx:nginx /etc/nginx
sed -i "s/80/8080" /etc/nginx/sites-available/default
chmod +w /etc/nginx/nginx.conf
su -u nginx service nginx start